FILES = utility.py \
	transform.py \
	Quaternion.py \
	jacobian.py \
	trajectory.py \
	kinematics.py \
	dynamics.py \
	Link.py \
	Robot.py \
	puma560.py \
	puma560akb.py \
	stanford.py \
	twolink.py

doc: $(FILES)
	epydoc $(FILES)
